services:
  - type: web
    name: pngfy-pro
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REMOVE_BG_API_KEY
        sync: false 